name: Update schedule
on:
  schedule:
    - cron: '0 0 * * *' # 每天 0 点 UTC 运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate schedule JSON
        run: |
          python .github/scripts/generate_schedule.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data/schedule.json
          git commit -m "Auto update schedule" || echo "No changes"
          git push